### ISSUE TITLE
reverse the spin

### ISSUE THREAD

**Issue by trade74** [Anurag-Kochar-1/Tech-stack-slot-machine#6]
Awesome repo BTW :-)

Can you easily reverse the spin, so that it starts from the top?
This is how slot machine work in my country so it will feel more natural.

**Comment by Anurag-Kochar-1** [comment]
Hey @trade74, thanks! Please check the site, the spin animation is now set to inverted, let me know if it feels more natural now :)

**Comment by trade74** [comment]
Yes feels more natural now, looks awesome :-p
